/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tanabe' at '15/11/10 20:50' with Gradle 2.7
 *
 * @author tanabe, @date 15/11/10 20:50
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
